services:
  kafka-1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CLUSTER_ID: spotify-cluster-001
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    ports:
      - "9092:9092"

  kafka-2:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      KAFKA_CLUSTER_ID: spotify-cluster-001
    volumes:
      - kafka-2-data:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096,CONTROLLER://0.0.0.0:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9096
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      KAFKA_CLUSTER_ID: spotify-cluster-001
    volumes:
      - kafka-3-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-1
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: spotify-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9094,kafka-3:9096

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka-1
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic listening_events --partitions 6 --replication-factor 3 --config retention.ms=604800000;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic p2p_network_events --partitions 6 --replication-factor 3;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic catalog_updates --partitions 3 --replication-factor 3 --config cleanup.policy=compact;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic enriched_events --partitions 6 --replication-factor 3;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic fraud_alerts --partitions 3 --replication-factor 3;
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic late_listening_events --partitions 3 --replication-factor 3;
      echo 'Topics Kafka crees';
      "

  spark-master:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8888
    ports:
      - "7077:7077"
      - "8888:8888"
    volumes:
      - ./spark_jobs:/opt/spark-jobs

  spark-worker-1:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    depends_on:
      - spark-master
    volumes:
      - ./spark_jobs:/opt/spark-jobs

  spark-worker-2:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    depends_on:
      - spark-master
    volumes:
      - ./spark_jobs:/opt/spark-jobs

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
